# Site settings
title: Soft-eng-practicum organization
email: cengique@users.sf.net
description: > # this means to ignore newlines until "baseurl:"
        This is an educational organization to host software development/engineering projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://soft-eng-practicum.github.io/" # the base hostname & protocol for your site
twitter_username: cengique
github_username:  cengique
theme: minima
repository: soft-eng-practicum/soft-eng-practicum.github.io
collections:
  itec3870_sp17:
    title: "Spring 2017 ITEC 3870 Soft Dev 2 course projects"
    date: 2017-05-10
    output: true
  itec3870_fa16:
    title: "Fall 2016 ITEC 3870 Soft Dev 2 course projects"
    date: 2016-12-01
    output: true

# Build settings
markdown: kramdown
