# Site settings
title: Software Engineering Practicum Organization
tagline: A collection of student created software projects
email: cengique@users.sf.net
description: > # this means to ignore newlines until "baseurl:"
        This is an educational organization to host software development/engineering projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://soft-eng-practicum.github.io/" # the base hostname & protocol for your site
twitter_username: cengique
github_username:  cengique
repository: soft-eng-practicum/soft-eng-practicum.github.io
collections:
  itec3870_fa18:
    title: "Fall 2018 ITEC 3870 Soft Dev 2 course projects"
    date: 2018-11-26
    output: true
  itec3870_sp18:
    title: "Spring 2018 ITEC 3870 Soft Dev 2 course projects"
    date: 2018-05-17
    output: true
  itec3870_fa17:
    title: "Fall 2017 ITEC 3870 Soft Dev 2 course projects"
    date: 2017-11-30
    output: true
  itec3870_sp17:
    title: "Spring 2017 ITEC 3870 Soft Dev 2 course projects"
    date: 2017-05-10
    output: true
  itec3870_fa16:
    title: "Fall 2016 ITEC 3870 Soft Dev 2 course projects"
    date: 2016-12-01
    output: true

# Build settings
markdown: kramdown
plugins:
  - jemoji
sass:
  style: expanded
