# Site settings
title: Soft-eng-practicum organization
email: cengique@users.sf.net
description: > # this means to ignore newlines until "baseurl:"
        This is an educational organization to host software development/engineering projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://soft-eng-practicum.github.io/" # the base hostname & protocol for your site
twitter_username: cengique
github_username:  cengique
theme: minima
repository: soft-eng-practicum

# Build settings
markdown: kramdown
